apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: Sampleapp
  name: Sample-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Sampleapp
  template:
    metadata:
      labels:
        app: Sampleapp
    spec:
      containers:
      - name: alpine
        image: Praveen/additem
		imagePullPolicy: Always
