apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledeployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - name: imageprod
        image: pkatdevops/firstimage
        ports:
        - containerPort: 3000
