apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledeployment
  namespace: bs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bs
  template:
    metadata:
      labels:
        app: bs
    spec:
      containers:
      - name: imageprod
        image: pkatdevops/firstimage
        ports:
        - containerPort: 3000
